# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_user_bundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:                        # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        api_doc:
            pattern: ^/api/doc/*            # All URLs are allowed
            anonymous: true                 # Anonymous access is allowed
        api:
            pattern: ^/                     # All URLs are protected
            fos_oauth: true                 # OAuth2 protected resource
            stateless: true                 # Do no set session cookies
            anonymous: false                # Anonymous access is not allowed
